# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'SDWebImage'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'MagicalRecord', '~> 2.3.0'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJExtension', '~> 3.0.10'
pod 'FMDB', '~> 2.6'
pod 'SocketRocket', '~> 0.4.2'
pod 'DateTools', '~> 1.7.0'
pod 'Reachability', '~> 3.2'
pod 'TTTAttributedLabel', '~> 1.13.4'
pod 'pop', '~> 1.0'
pod 'ReactiveCocoa','~>2.1.8'


  # 'node_modules'目录一般位于根目录中
  # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
  pod 'React', :path => '../RNPart/node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # 如果RN版本 >= 0.45则加入此行
    'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # 这个模块是用于调试功能的
    'RCTImage',
    'RCTAnimation',
    # 在这里继续添加你所需要的RN模块
  ]
  # 如果你的RN版本 >= 0.42.0，则加入下面这行
  pod "yoga", :path => "../RNPart/node_modules/react-native/ReactCommon/yoga"

   # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
  pod 'DoubleConversion', :podspec => '../RNPart/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../RNPart/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../RNPart/node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'CodePush', :podspec => '../RNPart/node_modules/react-native-code-push/CodePush.podspec'

target 'JasonDemo' do

end

target 'JasonDemo-测试环境' do
    
end

target 'JasonDemoTests' do

end

target 'JasonDemoUITests' do

end

